### ISSUE TITLE
NameError: name 'ma1' is not defined

### ISSUE THREAD

**Issue by x829901** [je-suis-tm/quant-trading#9]
When I run `MACD Oscillator backtest.py` for Apple Inc. (AAPL), I get a NameError. 

```
ma1:11
ma2:29
start date in format yyyy-mm-dd:2019-03-18
end date in format yyyy-mm-dd:2020-03-18
ticker:AAPL
slicing:10
[*********************100%***********************]  1 of 1 completed
Traceback (most recent call last):
  File "C:/Users/25del/PycharmProjects/KrakenBot/MACD.py", line 134, in <module>
    main()
  File "C:/Users/25del/PycharmProjects/KrakenBot/MACD.py", line 124, in main
    new = signal_generation(df, macd)
  File "C:/Users/25del/PycharmProjects/KrakenBot/MACD.py", line 37, in signal_generation
    signals = method(df)
  File "C:/Users/25del/PycharmProjects/KrakenBot/MACD.py", line 21, in macd
    signals['ma1'] = signals['Close'].rolling(window=ma1, min_periods=1, center=False).mean()
NameError: name 'ma1' is not defined
```

**Comment by je-suis-tm** [comment]
Thx for pointing out, I have set them as global variables.
